import {
  AnimalColumns,
  UserStocksColumns,
  CarsColumns,
} from "data/src/types/Columns";

export const animalColumns: AnimalColumns = {
  uuid: {
    columnName: "uuid",
    parent: undefined,
    isEditable: false,
    isImage: false,
    isColor: false,
    isButton: false,
    isCheckBox: false,
  },
  name: {
    columnName: "Name",
    parent: "animal",
    isEditable: true,
    isImage: false,
    isColor: false,
    isButton: false,
    isCheckBox: false,
  },
  type: {
    columnName: "Type",
    parent: "animal",
    isEditable: true,
    isImage: false,
    isColor: false,
    isButton: false,
    isCheckBox: false,
  },
  gender: {
    columnName: "Gender",
    parent: "animal",
    isEditable: true,
    isImage: false,
    isColor: false,
    isButton: false,
    isCheckBox: false,
  },
  image: {
    columnName: "Image",
    parent: "animal",
    isEditable: true,
    isImage: true,
    isColor: false,
    isButton: false,
    isCheckBox: false,
  },
  isSelected: {
    columnName: "IsSelected",
    parent: "animal",
    isEditable: false,
    isImage: false,
    isColor: false,
    isButton: false,
    isCheckBox: true,
  },
  latitude: {
    columnName: "Latitude",
    parent: "animal",
    isEditable: true,
    isImage: false,
    isColor: false,
    isButton: false,
    isCheckBox: false,
  },
  longitude: {
    columnName: "Longitude",
    parent: "animal",
    isEditable: true,
    isImage: false,
    isColor: false,
    isButton: false,
    isCheckBox: false,
  },
};

export const userStocksColumns: UserStocksColumns = {
  uuid: {
    columnName: "uuid",
    parent: undefined,
    isEditable: false,
    isImage: false,
    isColor: false,
    isButton: false,
    isCheckBox: false,
  },
  first_name: {
    columnName: "First Name",
    parent: undefined,
    isEditable: false,
    isImage: false,
    isColor: false,
    isButton: false,
    isCheckBox: false,
  },
  last_name: {
    columnName: "Last Name",
    parent: undefined,
    isEditable: false,
    isImage: false,
    isColor: false,
    isButton: false,
    isCheckBox: false,
  },
  email: {
    columnName: "Email",
    parent: undefined,
    isEditable: false,
    isImage: false,
    isColor: false,
    isButton: false,
    isCheckBox: false,
  },
  gender: {
    columnName: "Gender",
    parent: undefined,
    isEditable: false,
    isImage: false,
    isColor: false,
    isButton: false,
    isCheckBox: false,
  },
  isSelected: {
    columnName: "IsSelected",
    parent: undefined,
    isEditable: true,
    isImage: false,
    isColor: false,
    isButton: false,
    isCheckBox: true,
  },
  ticker: {
    columnName: "Ticker",
    parent: "stock",
    isEditable: true,
    isImage: false,
    isColor: false,
    isButton: false,
    isCheckBox: false,
  },
  name: {
    columnName: "Name",
    parent: "stock",
    isEditable: true,
    isImage: false,
    isColor: false,
    isButton: false,
    isCheckBox: false,
  },
  marketCap: {
    columnName: "MarketCap",
    parent: "stock",
    isEditable: true,
    isImage: false,
    isColor: false,
    isButton: false,
    isCheckBox: false,
  },
  price: {
    columnName: "Price",
    parent: "stock",
    isEditable: true,
    isImage: false,
    isColor: false,
    isButton: false,
    isCheckBox: false,
  },
  isOwned: {
    columnName: "IsOwned",
    parent: "stock",
    isEditable: true,
    isImage: false,
    isColor: false,
    isButton: false,
    isCheckBox: true,
  },
  isWatching: {
    columnName: "IsWatching",
    parent: "stock",
    isEditable: true,
    isImage: false,
    isColor: false,
    isButton: false,
    isCheckBox: true,
  },
};

export const carsColumns: CarsColumns = {
  uuid: {
    columnName: "uuid",
    parent: undefined,
    isEditable: false,
    isImage: false,
    isColor: false,
    isButton: false,
    isCheckBox: false,
  },
  name: {
    columnName: "Name",
    parent: "car",
    isEditable: true,
    isImage: false,
    isColor: false,
    isButton: false,
    isCheckBox: false,
  },
  make: {
    columnName: "Make",
    parent: "car",
    isEditable: false,
    isImage: false,
    isColor: false,
    isButton: false,
    isCheckBox: false,
  },
  model: {
    columnName: "Model",
    parent: "car",
    isEditable: false,
    isImage: false,
    isColor: false,
    isButton: false,
    isCheckBox: false,
  },
  vin: {
    columnName: "Vin",
    parent: "car",
    isEditable: false,
    isImage: false,
    isColor: false,
    isButton: false,
    isCheckBox: false,
  },
  year: {
    columnName: "Year",
    parent: "car",
    isEditable: false,
    isImage: false,
    isColor: false,
    isButton: false,
    isCheckBox: false,
  },
  isSelected: {
    columnName: "IsSelected",
    parent: "car",
    isEditable: true,
    isImage: false,
    isColor: false,
    isButton: false,
    isCheckBox: true,
  },
  image: {
    columnName: "Image",
    parent: "car",
    isEditable: true,
    isImage: true,
    isColor: false,
    isButton: false,
    isCheckBox: false,
  },
};
